services:
  simulation_env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytorch_quant_env
    volumes:
      - ../src:/app
      - ../data:/app/data
    environment:
      - OMP_NUM_THREADS=1
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true